#!/usr/bin/python
#By @seguridadblanca


import urllib2
import time

uri = "http://www.fifa.com/worldcup/videos/goal-of-the-tournament/gotOperations.htmx?action=save&idm=null&idp=2404190-&ida=2389158-F5"

headers= {'User-Agent' : 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/28.0.1500.71 Chrome/28.0.1500.71 Safari/537.36'}

for x in range (10):
pet = urllib2.Request(uri, None, headers)
code = urllib2.urlopen(pet).read()
print code
time.sleep(1)
